import { get, put } from '../../src/server/storage.js';

type Store = 'camapua' | 'newfit';
export type CashSale = { checkoutId: string; orderId: number; orderNumber?: number; at: string; operatorId: string; operatorName: string; sellerId: number; sellerName?: string | null; payment: string; total: number; documentChoice?: string | null };
export type CashHandoff = { id: string; fromUserId: string; fromUserName: string; at: string; expectedByPayment: Record<string, number>; deliveredByPayment: Record<string, number>; expectedTotal: number; deliveredTotal: number; divergence: number; notes?: string };
export type CashFinalClose = { closedByUserId: string; closedByName: string; closedAt: string; expectedByPayment: Record<string, number>; deliveredByPayment: Record<string, number>; expectedTotal: number; deliveredTotal: number; divergence: number; notes?: string };
export type CashSession = { id: string; store: Store; register: string; businessDate: string; openedByUserId: string; openedByName: string; openedAt: string; openingAmount: number; status: 'OPEN' | 'CLOSED'; blingSnapshot?: any; sales: CashSale[]; handoffs: CashHandoff[]; finalClose?: CashFinalClose };
const key = (store: Store, date: string) => `pdv/cash/${store}/${date}.json`;
export async function loadCashSession(store: Store, date: string) { try { const result = await get(key(store, date)); if (!result?.stream) return null; const raw = JSON.parse(await new Response(result.stream).text()) as Partial<CashSession>; return { ...raw, sales: Array.isArray(raw.sales) ? raw.sales : [], handoffs: Array.isArray(raw.handoffs) ? raw.handoffs : [] } as CashSession; } catch (error: any) { if (error?.statusCode === 404) return null; throw error; } }
export async function saveCashSession(session: CashSession) { await put(key(session.store, session.businessDate), JSON.stringify(session, null, 2), { contentType: 'application/json' }); return session; }
export function newCashSession(input: { store: Store; date: string; userId: string; userName: string; openingAmount: number; blingSnapshot?: any }): CashSession { return { id: `cash_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`, store: input.store, register: 'CAIXA 01', businessDate: input.date, openedByUserId: input.userId, openedByName: input.userName, openedAt: new Date().toISOString(), openingAmount: Number.isFinite(input.openingAmount) ? input.openingAmount : 0, status: 'OPEN', blingSnapshot: input.blingSnapshot, sales: [], handoffs: [] }; }
export function paymentKey(value: string) { const x = String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase(); if (x.includes('PIX')) return 'pix'; if (x.includes('DINHEIRO') || x.includes('ESPECIE')) return 'cash'; if (x.includes('BEMOL')) return 'bemol'; if (x.includes('DEBITO')) return 'debit'; if (x.includes('CREDITO') || x.includes('CARTAO')) return 'credit'; return 'other'; }
export function paymentBreakdown(sales: CashSale[]) { const result: Record<string, number> = { pix: 0, cash: 0, credit: 0, debit: 0, bemol: 0, other: 0 }; for (const sale of sales) result[paymentKey(sale.payment)] += Number(sale.total) || 0; return result; }
export function sumBreakdown(v: Record<string, number>) { return Object.values(v).reduce((sum, n) => sum + (Number(n) || 0), 0); }
export function divergence(expected: Record<string, number>, delivered: Record<string, number>) { const keys = new Set([...Object.keys(expected), ...Object.keys(delivered)]); let total = 0; for (const k of keys) total += (Number(delivered[k]) || 0) - (Number(expected[k]) || 0); return Number(total.toFixed(2)); }
