import { json, readJsonBody } from '../../src/server/bling-shared.js';
import { getBlingAccessToken } from '../../src/server/bling-client.js';
import { createUserRecord, findUser, loadUsers, publicUser, saveUsers, verifyPassword, sessionCookie, clearSessionCookie, sessionUser, recoveryToken, recoveryHash, recoveryTtlMs, assertPassword } from '../lib/pdv-auth.js';

type AnyRecord = Record<string, any>;
const API_BASE = 'https://api.bling.com.br/Api/v3';
const STORE_DEFINITIONS = [{ key: 'CAMAPUA', name: 'CAMAPUÃ', stock: 'ESTOQUE MATRIZ', channelId: 206151819 }, { key: 'NEWFIT', name: 'NEWFIT', stock: 'ESTOQUE NEWFIT', channelId: 206151809 }];
function normalize(value: unknown) { return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toUpperCase(); }
function amount(value: unknown) { const number = Number(value); return Number.isFinite(number) ? number : 0; }
function numericField(order: AnyRecord, candidates: unknown[]) { for (const candidate of candidates) if (candidate !== undefined && candidate !== null && candidate !== '') return { available: true, value: amount(candidate) }; return { available: false, value: 0 }; }
function valueBreakdown(order: AnyRecord) { const total = amount(order?.total); const before = numericField(order, [order?.subtotal, order?.subtotalProdutos, order?.valorProdutos, order?.totalProdutos, order?.valorBruto, order?.valorTotalSemDesconto]); const discount = numericField(order, [order?.desconto?.valor, order?.valorDesconto, order?.desconto]); if (before.available) return { available: true, before: before.value, discount: discount.available ? discount.value : Math.max(0, before.value - total), total }; if (discount.available) return { available: true, before: total + discount.value, discount: discount.value, total }; return { available: false, before: 0, discount: 0, total }; }
function isAttended(order: AnyRecord) { const situation = order?.situacao ?? {}; const configuredId = process.env.BLING_ATENDIDO_SITUACAO_ID?.trim(); if (configuredId && String(situation.id ?? '') === configuredId) return true; return [situation.nome, situation.descricao, situation.valor, order?.situacaoNome, order?.status].some(value => normalize(value) === 'ATENDIDO'); }
function storeFor(order: AnyRecord) { const channelId = Number(order?.loja?.id || 0); const byChannel = STORE_DEFINITIONS.find(store => store.channelId === channelId); if (byChannel) return byChannel; const candidates = [order?.unidadeNegocio?.nome, order?.loja?.nome, order?.unidadeNegocio?.descricao, order?.loja?.descricao].map(normalize); if (candidates.some(value => value.includes('CAMAPUA'))) return STORE_DEFINITIONS[0]; if (candidates.some(value => value.includes('NEWFIT'))) return STORE_DEFINITIONS[1]; return null; }
function paymentBucket(description: unknown) { const value = normalize(description); if (!value) return null; if (value.includes('PIX')) return 'pix'; if (value.includes('DINHEIRO') || value.includes('ESPECIE')) return 'cash'; if (value.includes('BEMOL')) return 'bemol'; if (value.includes('DEBITO')) return 'debit'; if (value.includes('CREDITO') || value.includes('CARTAO')) return 'credit'; return null; }
function addPayments(target: AnyRecord, order: AnyRecord) { const parcels = Array.isArray(order?.parcelas) ? order.parcelas : []; for (const parcel of parcels) { const description = parcel?.formaPagamento?.descricao ?? parcel?.formaPagamento?.nome ?? parcel?.formaPagamento?.tipo ?? parcel?.descricao; const bucket = paymentBucket(description); if (bucket) target[bucket] += amount(parcel?.valor ?? parcel?.valorPago ?? parcel?.valorParcela); } return parcels.length > 0; }
async function blingGet(token: string, path: string) { const response = await fetch(`${API_BASE}${path}`, { headers: { Accept: '1.0', Authorization: `Bearer ${token}`, 'enable-jwt': '1' } }); const text = await response.text(); let body: AnyRecord = {}; try { body = text ? JSON.parse(text) : {}; } catch { body = { error: text }; } if (!response.ok) { const detail = body?.error?.message || body?.message || body?.error || `HTTP ${response.status}`; const error = new Error(String(detail)); (error as AnyRecord).status = response.status; throw error; } return body; }
async function requireAdmin(request: Request) { const user = await sessionUser(request); return user?.role === 'ADMIN' ? user : null; }
async function sendRecoveryEmail(user: any, token: string) { const apiKey = process.env.RESEND_API_KEY; if (!apiKey) throw new Error('RESEND_API_KEY não configurada.'); const base = process.env.PUBLIC_APP_URL || 'https://www.capitaosuplementos.com.br'; const url = `${base.replace(/\/$/, '')}/admin?recover=${encodeURIComponent(token)}`; const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: process.env.RESEND_FROM_EMAIL || 'Capitão Suplementos <noreply@capitaosuplementos.com.br>', to: [user.email], subject: 'Recuperação de senha — Capitão Suplementos', html: `<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto"><h2>Recuperação de acesso</h2><p>Olá, ${user.name}.</p><p>Recebemos uma solicitação para criar uma nova senha para seu acesso ao PDV.</p><p><a href="${url}" style="display:inline-block;padding:12px 18px;background:#b8862f;color:#fff;text-decoration:none;border-radius:8px">CRIAR NOVA SENHA</a></p><p>O link expira em 15 minutos e pode ser usado uma única vez.</p></div>`, text: `Recuperação de acesso\n\nAcesse ${url}\n\nO link expira em 15 minutos e pode ser usado uma única vez.` }) }); if (!response.ok) throw new Error(`Resend rejeitou o envio: ${await response.text()}`); }

export async function GET(request: Request) {
  const url = new URL(request.url); const resource = url.searchParams.get('resource');
  if (resource === 'users') { const admin = await requireAdmin(request); if (!admin) return json({ error: 'Acesso administrativo necessário.' }, 401); try { const users = await loadUsers(); return json({ users: users.map(publicUser) }, 200, { 'Cache-Control': 'no-store' }); } catch (error) { return json({ error: error instanceof Error ? error.message : 'Não foi possível carregar usuários.' }, 503); } }
  if (resource === 'caixas') { try { const token = await getBlingAccessToken(); const params = new URLSearchParams(); for (const key of ['pagina','limite','dataInicial','dataFinal','situacaoConciliacao']) { const value = url.searchParams.get(key); if (value) params.set(key, value); } const data = await blingGet(token, `/caixas${params.toString() ? `?${params.toString()}` : ''}`); return json({ source: 'bling', ...data }, 200, { 'Cache-Control': 'private, max-age=30' }); } catch (error) { const status = Number((error as AnyRecord)?.status) || 503; return json({ error: error instanceof Error ? error.message : 'Não foi possível consultar os caixas do Bling.' }, status >= 400 && status < 600 ? status : 503); } }
  const date = url.searchParams.get('data') || new Date().toISOString().slice(0, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return json({ error: 'Data inválida. Use AAAA-MM-DD.' }, 400);
  try { const token = await getBlingAccessToken(); const stores = STORE_DEFINITIONS.map(store => ({ name: store.name, stock: store.stock, sales: 0, total: 0, beforeDiscount: 0, discount: 0, pix: 0, cash: 0, credit: 0, debit: 0, bemol: 0 })); let attended = 0, gross = 0, beforeDiscount = 0, discount = 0, valueBreakdownAvailable = true, paymentBreakdownAvailable = true, page = 1; while (page <= 50) { const params = new URLSearchParams({ pagina: String(page), limite: '100', dataInicial: date, dataFinal: date }); const result = await blingGet(token, `/pedidos/vendas?${params.toString()}`); const orders = Array.isArray(result?.data) ? result.data : []; if (!orders.length) break; for (const order of orders) { if (!isAttended(order)) continue; attended += 1; const breakdown = valueBreakdown(order); gross += breakdown.total; if (breakdown.available) { beforeDiscount += breakdown.before; discount += breakdown.discount; } else valueBreakdownAvailable = false; const store = storeFor(order); if (!store) continue; const target = stores.find(item => item.name === store.name); if (!target) continue; target.sales += 1; target.total += breakdown.total; if (breakdown.available) { target.beforeDiscount += breakdown.before; target.discount += breakdown.discount; } if (!addPayments(target, order)) paymentBreakdownAvailable = false; } if (orders.length < 100) break; page += 1; await new Promise(resolve => setTimeout(resolve, 350)); } return json({ date, stores, sales: attended, total: gross, beforeDiscount: valueBreakdownAvailable ? beforeDiscount : null, discount: valueBreakdownAvailable ? discount : null, valueBreakdownAvailable, paymentBreakdownAvailable }); } catch (error) { const status = Number((error as AnyRecord)?.status) || 500; console.error('PDV report Bling error:', error); return json({ error: error instanceof Error ? error.message : 'Não foi possível consultar o Bling.' }, status >= 400 && status < 600 ? status : 500); }
}

export async function POST(request: Request) {
  const resource = new URL(request.url).searchParams.get('resource');
  try {
    const body = await readJsonBody(request) as AnyRecord;
    if (resource === 'bootstrap-admin') { const users = await loadUsers(); if (users.length) return json({ error: 'O administrador inicial já foi criado.' }, 409); const user = createUserRecord({ name: body.name, username: body.username, email: body.email, password: body.password, role: 'ADMIN' }); await saveUsers([user]); return json({ ok: true, user: publicUser(user) }, 201, { 'Set-Cookie': sessionCookie(user) }); }
    if (resource === 'login') { const users = await loadUsers(); const user = findUser(users, body.identifier); if (!user || !user.active || !verifyPassword(String(body.password || ''), user.passwordSalt, user.passwordHash)) return json({ error: 'Usuário ou senha inválidos.' }, 401); return json({ ok: true, user: publicUser(user) }, 200, { 'Set-Cookie': sessionCookie(user) }); }
    if (resource === 'logout') return json({ ok: true }, 200, { 'Set-Cookie': clearSessionCookie() });
    if (resource === 'recover-request') { const users = await loadUsers(); const user = findUser(users, body.email); if (!user || !user.active) return json({ ok: true }, 200); const token = recoveryToken(); user.recoveryHash = recoveryHash(token); user.recoveryExpiresAt = Date.now() + recoveryTtlMs; user.updatedAt = new Date().toISOString(); await saveUsers(users); await sendRecoveryEmail(user, token); return json({ ok: true }); }
    if (resource === 'recover-reset') { const users = await loadUsers(); const hash = recoveryHash(String(body.token || '')); const user = users.find(item => item.active && item.recoveryHash === hash && Number(item.recoveryExpiresAt || 0) > Date.now()); if (!user) return json({ error: 'Link de recuperação inválido ou expirado.' }, 400); const next = createUserRecord({ name: user.name, username: user.username, email: user.email, password: body.password, role: user.role, active: user.active, blingSellerId: user.blingSellerId, blingSellerName: user.blingSellerName }); user.passwordHash = next.passwordHash; user.passwordSalt = next.passwordSalt; user.recoveryHash = undefined; user.recoveryExpiresAt = undefined; user.updatedAt = new Date().toISOString(); await saveUsers(users); return json({ ok: true }); }
    const admin = await requireAdmin(request); if (!admin) return json({ error: 'Acesso administrativo necessário.' }, 401);
    if (resource === 'user-create') { const users = await loadUsers(); const username = String(body.username || '').trim(); const email = String(body.email || '').trim().toLowerCase(); if (!body.name || !username || !email || !body.password) return json({ error: 'Nome, usuário, e-mail e senha são obrigatórios.' }, 400); if (users.some(user => user.username.toLowerCase() === username.toLowerCase() || user.email.toLowerCase() === email)) return json({ error: 'Usuário ou e-mail já cadastrado.' }, 409); const user = createUserRecord({ name: body.name, username, email, password: body.password, role: body.role === 'ADMIN' ? 'ADMIN' : 'OPERATOR', active: body.active !== false, blingSellerId: body.blingSellerId, blingSellerName: body.blingSellerName }); users.push(user); await saveUsers(users); return json({ ok: true, user: publicUser(user) }, 201); }
    if (resource === 'user-update') { const users = await loadUsers(); const user = users.find(item => item.id === body.id); if (!user) return json({ error: 'Usuário não encontrado.' }, 404); if (body.name !== undefined) user.name = String(body.name).trim(); if (body.email !== undefined) user.email = String(body.email).trim().toLowerCase(); if (body.active !== undefined) user.active = Boolean(body.active); if (body.role === 'ADMIN' || body.role === 'OPERATOR') user.role = body.role; if (body.blingSellerId !== undefined) user.blingSellerId = Number(body.blingSellerId) > 0 ? Number(body.blingSellerId) : null; if (body.blingSellerName !== undefined) user.blingSellerName = String(body.blingSellerName || '').trim() || null; if (body.password) { const next = createUserRecord({ name: user.name, username: user.username, email: user.email, password: body.password }); user.passwordHash = next.passwordHash; user.passwordSalt = next.passwordSalt; } user.updatedAt = new Date().toISOString(); await saveUsers(users); return json({ ok: true, user: publicUser(user) }); }
    if (resource === 'user-reset') { const users = await loadUsers(); const user = users.find(item => item.id === body.id); if (!user) return json({ error: 'Usuário não encontrado.' }, 404); const token = recoveryToken(); user.recoveryHash = recoveryHash(token); user.recoveryExpiresAt = Date.now() + recoveryTtlMs; user.updatedAt = new Date().toISOString(); await saveUsers(users); await sendRecoveryEmail(user, token); return json({ ok: true }); }
    return json({ error: 'Recurso não informado.' }, 400);
  } catch (error) { console.error('PDV auth/admin error:', error); return json({ error: error instanceof Error ? error.message : 'Não foi possível processar a operação.' }, 500); }
}
