import { json, readJsonBody } from '../../src/server/bling-shared.js';
import { getBlingAccessToken } from '../../src/server/bling-client.js';
import { createUserRecord, findUser, loadUsers, publicUser, saveUsers, verifyPassword, sessionCookie, clearSessionCookie, sessionUser, recoveryToken, recoveryHash, recoveryTtlMs } from '../lib/pdv-auth.js';
import { loadCashSession, newCashSession, saveCashSession } from '../lib/pdv-cash.js';
type R=Record<string,any>; const BASE='https://api.bling.com.br/Api/v3'; const STORES=[{key:'camapua',name:'CAMAPUÃ',stock:'ESTOQUE MATRIZ',channelId:206151819},{key:'newfit',name:'NEWFIT',stock:'ESTOQUE NEWFIT',channelId:206151809}];
const norm=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase(); const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
async function bg(token:string,path:string){const r=await fetch(BASE+path,{headers:{Accept:'1.0',Authorization:`Bearer ${token}`,'enable-jwt':'1'}});const t=await r.text();let d:R={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok){const e=new Error(String(d?.error?.message||d?.message||d?.error||`HTTP ${r.status}`));(e as any).status=r.status;throw e}return d}
function breakdown(o:R){const total=num(o?.total),b=[o?.subtotal,o?.subtotalProdutos,o?.valorProdutos,o?.totalProdutos,o?.valorBruto,o?.valorTotalSemDesconto].find(x=>x!==undefined&&x!==null&&x!=='');const dis=[o?.desconto?.valor,o?.valorDesconto,o?.desconto].find(x=>x!==undefined&&x!==null&&x!=='');if(b!==undefined)return {available:true,before:num(b),discount:dis!==undefined?num(dis):Math.max(0,num(b)-total),total};if(dis!==undefined)return {available:true,before:total+num(dis),discount:num(dis),total};return {available:false,before:0,discount:0,total}}
function attended(o:R){const s=o?.situacao||{},id=process.env.BLING_ATENDIDO_SITUACAO_ID?.trim();if(id&&String(s.id||'')===id)return true;return [s.nome,s.descricao,s.valor,o?.situacaoNome,o?.status].some(v=>norm(v)==='ATENDIDO')}
function storeFor(o:R){const id=Number(o?.loja?.id||0),s=STORES.find(x=>x.channelId===id);if(s)return s;const a=[o?.unidadeNegocio?.nome,o?.loja?.nome,o?.unidadeNegocio?.descricao,o?.loja?.descricao].map(norm);return a.some(v=>v.includes('CAMAPUA'))?STORES[0]:a.some(v=>v.includes('NEWFIT'))?STORES[1]:null}
function pay(v:any){const x=norm(v);if(x.includes('PIX'))return'pix';if(x.includes('DINHEIRO')||x.includes('ESPECIE'))return'cash';if(x.includes('BEMOL'))return'bemol';if(x.includes('DEBITO'))return'debit';if(x.includes('CREDITO')||x.includes('CARTAO'))return'credit';return null}
function addPay(t:R,o:R){const p=Array.isArray(o?.parcelas)?o.parcelas:[];for(const q of p){const b=pay(q?.formaPagamento?.descricao??q?.formaPagamento?.nome??q?.formaPagamento?.tipo??q?.descricao);if(b)t[b]+=num(q?.valor??q?.valorPago??q?.valorParcela)}return p.length>0}
async function admin(req:Request){const u=await sessionUser(req);return u?.role==='ADMIN'?u:null}
async function mail(u:any,token:string){const key=process.env.RESEND_API_KEY;if(!key)throw new Error('RESEND_API_KEY não configurada.');const base=(process.env.PUBLIC_APP_URL||'https://www.capitaosuplementos.com.br').replace(/\/$/,'');const url=`${base}/admin?recover=${encodeURIComponent(token)}`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM_EMAIL||'Capitão Suplementos <noreply@capitaosuplementos.com.br>',to:[u.email],subject:'Recuperação de senha — Capitão Suplementos',html:`<p>Olá, ${u.name}.</p><p><a href="${url}">CRIAR NOVA SENHA</a></p><p>O link expira em 15 minutos e pode ser usado uma única vez.</p>`})});if(!r.ok)throw new Error('Não foi possível enviar o e-mail de recuperação.')}
export async function GET(req:Request){const u=new URL(req.url),resource=u.searchParams.get('resource');
 if(resource==='session'){const user=await sessionUser(req);return json({user:user?publicUser(user):null},200,{'Cache-Control':'no-store'})}
 if(resource==='users'){if(!await admin(req))return json({error:'Acesso administrativo necessário.'},401);try{return json({users:(await loadUsers()).map(publicUser)},200,{'Cache-Control':'no-store'})}catch(e){return json({error:e instanceof Error?e.message:'Não foi possível carregar usuários.'},503)}}
 if(resource==='cash-session'){const user=await sessionUser(req);if(!user)return json({error:'Login do PDV necessário.'},401);const store=(u.searchParams.get('store')||'camapua') as 'camapua'|'newfit';if(!['camapua','newfit'].includes(store))return json({error:'Loja inválida.'},400);try{const date=new Date().toISOString().slice(0,10);return json({cash:await loadCashSession(store,date),businessDate:date},200,{'Cache-Control':'no-store'})}catch(e){return json({error:e instanceof Error?e.message:'Não foi possível consultar o caixa.'},503)}}
 if(resource==='caixas'){try{const d=await bg(await getBlingAccessToken(),`/caixas?${u.searchParams.toString()}`);return json({source:'bling',...d},200,{'Cache-Control':'private,max-age=30'})}catch(e){const s=Number((e as any).status)||503;return json({error:e instanceof Error?e.message:'Não foi possível consultar os caixas do Bling.'},s)}}
 const date=u.searchParams.get('data')||new Date().toISOString().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return json({error:'Data inválida. Use AAAA-MM-DD.'},400);try{const token=await getBlingAccessToken(),stores=STORES.map(s=>({name:s.name,stock:s.stock,sales:0,total:0,beforeDiscount:0,discount:0,pix:0,cash:0,credit:0,debit:0,bemol:0}));let sales=0,total=0,before=0,discount=0,va=true,pa=true,page=1;while(page<=50){const d=await bg(token,`/pedidos/vendas?pagina=${page}&limite=100&dataInicial=${date}&dataFinal=${date}`),orders=Array.isArray(d?.data)?d.data:[];if(!orders.length)break;for(const o of orders){if(!attended(o))continue;sales++;const b=breakdown(o);total+=b.total;if(b.available){before+=b.before;discount+=b.discount}else va=false;const st=storeFor(o);if(!st)continue;const t=stores.find(x=>x.name===st.name)!;t.sales++;t.total+=b.total;if(b.available){t.beforeDiscount+=b.before;t.discount+=b.discount}if(!addPay(t,o))pa=false}if(orders.length<100)break;page++;await new Promise(r=>setTimeout(r,350))}return json({date,stores,sales,total,beforeDiscount:va?before:null,discount:va?discount:null,valueBreakdownAvailable:va,paymentBreakdownAvailable:pa})}catch(e){const s=Number((e as any).status)||500;return json({error:e instanceof Error?e.message:'Não foi possível consultar o Bling.'},s)}}
export async function POST(req:Request){const resource=new URL(req.url).searchParams.get('resource');try{const body=await readJsonBody(req) as R;
 if(resource==='bootstrap-admin'){const users=await loadUsers();if(users.length)return json({error:'O administrador inicial já foi criado.'},409);const user=createUserRecord({name:body.name,username:body.username,email:body.email,password:body.password,role:'ADMIN'});await saveUsers([user]);return json({ok:true,user:publicUser(user)},201,{'Set-Cookie':sessionCookie(user)})}
 if(resource==='login'){const users=await loadUsers(),user=findUser(users,body.identifier);if(!user||!user.active||!verifyPassword(String(body.password||''),user.passwordSalt,user.passwordHash))return json({error:'Usuário ou senha inválidos.'},401);return json({ok:true,user:publicUser(user)},200,{'Set-Cookie':sessionCookie(user)})}
 if(resource==='logout')return json({ok:true},200,{'Set-Cookie':clearSessionCookie()});
 if(resource==='recover-request'){const users=await loadUsers(),user=findUser(users,body.email);if(user?.active){const token=recoveryToken();user.recoveryHash=recoveryHash(token);user.recoveryExpiresAt=Date.now()+recoveryTtlMs;user.updatedAt=new Date().toISOString();await saveUsers(users);await mail(user,token)}return json({ok:true})}
 if(resource==='recover-reset'){const users=await loadUsers(),h=recoveryHash(String(body.token||'')),user=users.find(x=>x.active&&x.recoveryHash===h&&Number(x.recoveryExpiresAt||0)>Date.now());if(!user)return json({error:'Link de recuperação inválido ou expirado.'},400);const n=createUserRecord({name:user.name,username:user.username,email:user.email,password:body.password,role:user.role,active:user.active,blingSellerId:user.blingSellerId,blingSellerName:user.blingSellerName});user.passwordHash=n.passwordHash;user.passwordSalt=n.passwordSalt;user.recoveryHash=undefined;user.recoveryExpiresAt=undefined;user.updatedAt=new Date().toISOString();await saveUsers(users);return json({ok:true})}
 const user=await sessionUser(req);if(!user)return json({error:'Login do PDV necessário.'},401);
 if(resource==='cash-open'){const store=body.store as 'camapua'|'newfit';if(!['camapua','newfit'].includes(store))return json({error:'Loja inválida.'},400);const date=new Date().toISOString().slice(0,10),existing=await loadCashSession(store,date);if(existing?.status==='OPEN')return json({error:`Já existe caixa aberto em ${store==='camapua'?'CAMAPUÃ':'NEWFIT'}.`},409);let blingSnapshot=null;try{blingSnapshot=await bg(await getBlingAccessToken(),`/caixas?dataInicial=${date}&dataFinal=${date}&limite=100`)}catch(e){console.warn('Bling caixa snapshot indisponível:',e)}const cash=newCashSession({store,date,userId:user.id,userName:user.name,openingAmount:Number(body.openingAmount)||0,blingSnapshot});await saveCashSession(cash);return json({cash},201)}
 if(resource==='user-create'||resource==='user-update'||resource==='user-reset'){if(user.role!=='ADMIN')return json({error:'Acesso administrativo necessário.'},403);const users=await loadUsers();if(resource==='user-create'){const username=String(body.username||'').trim(),email=String(body.email||'').trim().toLowerCase();if(!body.name||!username||!email||!body.password)return json({error:'Nome, usuário, e-mail e senha são obrigatórios.'},400);if(users.some(x=>x.username.toLowerCase()===username.toLowerCase()||x.email.toLowerCase()===email))return json({error:'Usuário ou e-mail já cadastrado.'},409);const n=createUserRecord({name:body.name,username,email,password:body.password,role:body.role==='ADMIN'?'ADMIN':'OPERATOR',active:body.active!==false,blingSellerId:body.blingSellerId,blingSellerName:body.blingSellerName});users.push(n);await saveUsers(users);return json({ok:true,user:publicUser(n)},201)}const n=users.find(x=>x.id===body.id);if(!n)return json({error:'Usuário não encontrado.'},404);if(resource==='user-reset'){const token=recoveryToken();n.recoveryHash=recoveryHash(token);n.recoveryExpiresAt=Date.now()+recoveryTtlMs;await saveUsers(users);await mail(n,token);return json({ok:true})}if(body.name!==undefined)n.name=String(body.name).trim();if(body.email!==undefined)n.email=String(body.email).trim().toLowerCase();if(body.active!==undefined)n.active=Boolean(body.active);if(body.role==='ADMIN'||body.role==='OPERATOR')n.role=body.role;if(body.blingSellerId!==undefined)n.blingSellerId=Number(body.blingSellerId)||null;if(body.blingSellerName!==undefined)n.blingSellerName=String(body.blingSellerName||'').trim()||null;if(body.password){const p=createUserRecord({name:n.name,username:n.username,email:n.email,password:body.password});n.passwordHash=p.passwordHash;n.passwordSalt=p.passwordSalt}n.updatedAt=new Date().toISOString();await saveUsers(users);return json({ok:true,user:publicUser(n)})}
 return json({error:'Recurso não informado.'},400)}catch(e){console.error('PDV report/auth error:',e);return json({error:e instanceof Error?e.message:'Não foi possível processar a operação.'},500)}}
