import { createHash, createHmac } from 'node:crypto';
import { get, put } from '@vercel/blob';
import { json, readJsonBody } from '../../src/server/bling-shared.js';
import { accountStorageKey, availablePoints, cleanupExpiredReservations, emptyPointsAccount, MIN_REDEMPTION_POINTS, pointsValue, REDEMPTION_RESERVATION_TTL_MS, PointsAccount } from '../../src/server/pontos.js';
function secret(){return process.env.CUSTOMER_SESSION_SECRET||process.env.BLOB_READ_WRITE_TOKEN||process.env.RESEND_API_KEY||'';}
function verify(request:Request){const token=(request.headers.get('authorization')||'').startsWith('Bearer ')?(request.headers.get('authorization')||'').slice(7).trim():'';const [payload,signature]=token.split('.');const s=secret();if(!payload||!signature||!s)return '';const expected=createHmac('sha256',s).update(payload).digest('base64url');if(signature!==expected)return '';try{const d=JSON.parse(Buffer.from(payload,'base64url').toString('utf8')) as {sub?:string;exp?:number};return d.sub&&d.exp&&Date.now()<=d.exp?d.sub:'';}catch{return '';}}
function blobOptions(){const token=process.env.BLOB_READ_WRITE_TOKEN;return {access:'private' as const,useCache:false,...(token?{token}:{})};}
async function loadAccount(customerKey:string){try{const result=await get(accountStorageKey(customerKey),blobOptions());if(!result?.stream)return emptyPointsAccount(customerKey);const parsed=JSON.parse(await new Response(result.stream).text());return {...emptyPointsAccount(customerKey),...parsed,customerKey,entries:Array.isArray(parsed.entries)?parsed.entries:[],reservations:Array.isArray(parsed.reservations)?parsed.reservations:[],bonuses:Array.isArray(parsed.bonuses)?parsed.bonuses:[],cycleEarned:Number(parsed.cycleEarned||0)} as PointsAccount;}catch{return emptyPointsAccount(customerKey);}}
async function saveAccount(account:PointsAccount){const token=process.env.BLOB_READ_WRITE_TOKEN;await put(accountStorageKey(account.customerKey),JSON.stringify(account),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...(token?{token}:{})});}
function action(request:Request){return new URL(request.url).pathname.split('/').filter(Boolean).pop()||'';}
export async function GET(request:Request){const a=action(request);const customerKey=verify(request);if(!customerKey)return json({error:'Sessão expirada. Faça a validação novamente.'},401);if(a==='account'){try{if(!process.env.BLOB_STORE_ID&&!process.env.BLOB_READ_WRITE_TOKEN)return json({error:'Armazenamento não configurado.'},503);const account=await loadAccount(customerKey);const nextMilestone=[200,400,600,800,1000].find(v=>v>account.cycleEarned)||1000;return json({customerKey,email:account.email||null,balance:account.balance,value:pointsValue(account.balance),lifetimeEarned:account.lifetimeEarned,lifetimeRedeemed:account.lifetimeRedeemed,cycleEarned:account.cycleEarned,cycleRemaining:Math.max(0,1000-account.cycleEarned),nextMilestone,bonuses:account.bonuses||[],entries:account.entries.slice(-50).reverse()},200,{'Cache-Control':'no-store'});}catch{return json({error:'Não foi possível consultar seus pontos.'},503);}}
if(a==='redeem'){const account=cleanupExpiredReservations(await loadAccount(customerKey));const available=availablePoints(account);return json({enabled:process.env.POINTS_REDEMPTION_ENABLED!=='false',minimumPoints:MIN_REDEMPTION_POINTS,availablePoints:available,availableValue:pointsValue(available),reservedPoints:account.balance-available},200,{'Cache-Control':'no-store'});}return json({error:'Ação de pontos não encontrada.'},404);}
export async function POST(request:Request){if(action(request)!=='redeem')return json({error:'Ação de pontos não encontrada.'},404);try{const customerKey=verify(request);if(!customerKey)return json({error:'Sessão expirada. Faça a validação novamente.'},401);if(process.env.POINTS_REDEMPTION_ENABLED==='false')return json({error:'A troca de pontos está temporariamente indisponível.'},409);const body=await readJsonBody(request) as {points?:number;checkoutId?:string};const points=Math.floor(Number(body.points||0));const checkoutId=String(body.checkoutId||'').trim();if(!checkoutId)return json({error:'Identificador do checkout não informado.'},400);if(!Number.isInteger(points)||points<MIN_REDEMPTION_POINTS)return json({error:`O resgate mínimo é de ${MIN_REDEMPTION_POINTS} pontos.`},400);const account=cleanupExpiredReservations(await loadAccount(customerKey));const existing=(account.reservations||[]).find(item=>item.checkoutId===checkoutId&&item.status==='reserved');if(existing)return json({reserved:true,reservationId:existing.id,points:existing.points,value:existing.value,expiresAt:existing.expiresAt},200);const available=availablePoints(account);if(points>available)return json({error:`Saldo disponível insuficiente. Você pode usar até ${available} pontos.`},409);const reservationId=createHash('sha256').update(`${customerKey}:${checkoutId}:${points}`).digest('hex').slice(0,24);const createdAt=new Date();const expiresAt=new Date(createdAt.getTime()+REDEMPTION_RESERVATION_TTL_MS);const reservation={id:reservationId,checkoutId,points,value:pointsValue(points),createdAt:createdAt.toISOString(),expiresAt:expiresAt.toISOString(),status:'reserved' as const};await saveAccount({...account,reservations:[...(account.reservations||[]),reservation],updatedAt:createdAt.toISOString()});return json({reserved:true,reservationId,points,value:reservation.value,expiresAt:reservation.expiresAt,availablePoints:available-points},201);}catch(error){return json({error:error instanceof Error?error.message:'Não foi possível reservar os pontos.'},503);}}
export async function DELETE(request:Request){if(action(request)!=='redeem')return json({error:'Ação de pontos não encontrada.'},404);try{const customerKey=verify(request);if(!customerKey)return json({error:'Sessão expirada. Faça a validação novamente.'},401);const body=await readJsonBody(request) as {checkoutId?:string;reservationId?:string};const checkoutId=String(body.checkoutId||'').trim();const reservationId=String(body.reservationId||'').trim();if(!checkoutId&&!reservationId)return json({error:'Informe a reserva que será liberada.'},400);const account=cleanupExpiredReservations(await loadAccount(customerKey));const reservations=(account.reservations||[]).map(item=>{const match=item.status==='reserved'&&((reservationId&&item.id===reservationId)||(checkoutId&&item.checkoutId===checkoutId));return match?{...item,status:'released' as const}:item;});await saveAccount({...account,reservations});return json({released:true},200);}catch(error){return json({error:error instanceof Error?error.message:'Não foi possível liberar a reserva.'},503);}}
