import { StrictMode, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import Root from './AdminRoute';
import CheckoutPage, { hasValidCheckoutSession } from './CheckoutPage';
import CheckoutIdentityPage from './CheckoutIdentityPage';
import CheckoutValidation from './CheckoutValidation';
import CheckoutLoyalty from './CheckoutLoyalty';
import ContaPage from './ContaPage';
import OrderPage from './OrderPage';
import ReconnectPage from './ReconnectPage';
import PdvAuthGate from './PdvAuthGate';
import PdvReport from './PdvReport';
import PdvClosingEnhancer from './PdvClosingEnhancer';
import PdvRecompraAlertsEnhancer from './PdvRecompraAlertsEnhancer';
import PdvRealSaleEnhancer from './PdvRealSaleEnhancer';
import './styles.css';
function registerAppWorker(){if(!('serviceWorker'in navigator))return;window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Service Worker Capitão:',error)))}
function CheckoutFlowBridge(){useEffect(()=>{const go=()=>{if(location.pathname==='/checkout'&&!hasValidCheckoutSession())location.replace('/reconnect')};go();const timer=window.setInterval(go,5000);if(location.pathname==='/'){const d=localStorage.getItem('capitao-verified-document'),e=localStorage.getItem('capitao-verified-email'),a=localStorage.getItem('capitao-verified-at');if((d||e)&&!a){localStorage.setItem('capitao-verified-at',String(Date.now()));try{if(JSON.parse(localStorage.getItem('capitao-cart')||'[]').length)location.replace('/checkout')}catch{}}}const checkout=()=>{document.querySelectorAll<HTMLButtonElement>('.cart-checkout').forEach(button=>{if(button.textContent!=='IR PARA O CHECKOUT')button.textContent='IR PARA O CHECKOUT';if(button.dataset.checkoutBound==='true')return;button.dataset.checkoutBound='true';button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();location.href=hasValidCheckoutSession()?'/checkout':'/cadastro'},true)})};const account=()=>{const link=document.querySelector<HTMLAnchorElement>('.header-login');if(!link)return;const logged=Boolean(localStorage.getItem('capitao-customer-session'));link.href=logged?'/conta':'/cadastro';const label=link.querySelector('span');if(label)label.textContent=logged?'Minha conta':'Login'};const order=()=>{if(location.pathname!=='/checkout')return;const success=document.querySelector<HTMLElement>('.checkout-success'),button=success?.querySelector<HTMLAnchorElement>('a.checkout-primary');if(!success||!button)return;button.textContent='CONTINUAR COMPRANDO';if(success.querySelector('.checkout-view-order'))return;const view=document.createElement('a');view.href='/pedido';view.className='checkout-primary checkout-view-order';view.textContent='VER PEDIDO';success.insertBefore(view,button)};checkout();account();order();const observer=new MutationObserver(()=>{checkout();account();order()});observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();window.clearInterval(timer)}},[]);return null}
function Page(){if(location.pathname==='/pdv')return <PdvAuthGate/>;if(location.pathname==='/pdvreport')return <PdvReport/>;if(location.pathname==='/checkout')return hasValidCheckoutSession()?<><CheckoutPage/><CheckoutLoyalty checkoutId={sessionStorage.getItem('capitao-checkout-id')||''} total={(()=>{try{return JSON.parse(localStorage.getItem('capitao-cart')||'[]').reduce((sum:number,item:{price?:string})=>{const n=String(item.price||'').replace(/[^0-9,]/g,'').replace(/\./g,'').replace(',','.');const v=Number(n);return sum+(Number.isFinite(v)?v:0)},0)}catch{return 0}})()}/></>:<ReconnectPage/>;if(location.pathname==='/reconnect')return <ReconnectPage/>;if(location.pathname==='/cadastro')return <CheckoutIdentityPage/>;if(location.pathname==='/conta')return <ContaPage/>;if(location.pathname==='/pedido')return <OrderPage/>;return <Root/>}
registerAppWorker();createRoot(document.getElementById('root')!).render(<StrictMode><Page/><CheckoutValidation/><CheckoutFlowBridge/><PdvClosingEnhancer/><PdvRecompraAlertsEnhancer/><PdvRealSaleEnhancer/></StrictMode>);
