import { useEffect, useState } from 'react';
import { ArrowRight, LockKeyhole, LogOut, Store } from 'lucide-react';
import Pdv from './Pdv';
type User={id:string;name:string;username:string;email:string;role:'ADMIN'|'OPERATOR';blingSellerId:number|null;blingSellerName:string|null}; type Cash={id:string;store:'camapua'|'newfit';register:string;businessDate:string;openedByName:string;openedAt:string;openingAmount:number;status:'OPEN'|'CLOSED';blingSnapshot?:any};
async function call(resource:string,body?:any){const r=await fetch(`/api/bling/pdv-report?resource=${resource}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Não foi possível processar.');return d}
const css=`.pdv-auth-shell{min-height:100vh;background:#0a0b0c;color:#f4f2ed;display:grid;place-items:center;padding:24px;font-family:Inter,ui-sans-serif,system-ui}.pdv-auth-card{width:min(430px,100%);background:#111314;border:1px solid #2d3032;border-radius:18px;padding:32px;box-shadow:0 28px 80px #0009}.pdv-auth-mark{display:flex;align-items:center;gap:8px;color:#bd9149;font-size:12px;font-weight:950;letter-spacing:1.8px;margin-bottom:22px}.pdv-auth-card h1{font-size:26px;margin:7px 0}.pdv-auth-card p{color:#85898e;font-size:12px;line-height:1.6;margin:0 0 22px}.pdv-auth-card label{display:block;color:#8c9196;font-size:9px;font-weight:900;letter-spacing:.8px;margin:12px 0}.pdv-auth-card input{display:block;width:100%;height:46px;margin-top:7px;background:#191b1c;border:1px solid #34373a;border-radius:9px;color:#fff;padding:0 13px;outline:0}.pdv-auth-card input:focus{border-color:#b88a3d}.pdv-auth-submit{width:100%;height:46px;border:0;border-radius:9px;background:#b4863d;color:#fff;font-weight:950;font-size:10px;letter-spacing:1px;display:flex;align-items:center;justify-content:center;gap:8px;margin-top:18px;cursor:pointer}.pdv-auth-submit:disabled{opacity:.4;cursor:not-allowed}.pdv-auth-error{background:#2a1717;border:1px solid #6a3333;color:#e8aaa5;padding:11px;border-radius:9px;font-size:10px}.pdv-auth-success{background:#17251b;border:1px solid #315a3d;color:#a9d8b4;padding:11px;border-radius:9px;font-size:10px}.pdv-auth-link{display:block;text-align:center;margin-top:14px;color:#b99045;font-size:9px;font-weight:850;text-decoration:none;background:transparent;border:0;width:100%;cursor:pointer}.pdv-admin-link{display:block;text-align:center;margin-top:17px;color:#777b80;font-size:10px;text-decoration:none}.pdv-store-toggle{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:16px 0}.pdv-store-toggle button{height:40px;border:1px solid #34373a;background:#181a1b;color:#8d9297;border-radius:8px;font-size:9px;font-weight:900;cursor:pointer}.pdv-store-toggle button.active{border-color:#b88a3d;background:#211b12;color:#e6c994}.pdv-cash-card small{display:block;color:#72777c;font-size:9px;line-height:1.6;margin-top:14px}.pdv-logout{border:0;background:transparent;color:#777b80;display:flex;align-items:center;gap:6px;margin:15px auto 0;font-size:9px;cursor:pointer}.pdv-session-chip{position:fixed;right:76px;top:17px;z-index:80;border:1px solid #34373a;background:#17191a;color:#bbb;border-radius:999px;padding:8px 11px;font-size:9px;display:flex;align-items:center;gap:6px;cursor:pointer}.pdv-session-chip:hover{border-color:#b88a3d;color:#eee}`;
export default function PdvAuthGate(){const[user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);const[identifier,setIdentifier]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[success,setSuccess]=useState('');const[mode,setMode]=useState<'login'|'recover'|'reset'>(new URLSearchParams(location.search).has('recover')?'reset':'login');const[cash,setCash]=useState<Cash|null>(null);const[store,setStore]=useState<'camapua'|'newfit'>('camapua');const[opening,setOpening]=useState('');const[cashLoading,setCashLoading]=useState(false);
 async function loadCash(s=store){try{const d=await call(`cash-session&store=${s}`);setCash(d.cash||null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível consultar o caixa.')}}
 useEffect(()=>{(async()=>{try{const d=await call('session');setUser(d.user||null);if(d.user)await loadCash()}catch{}finally{setLoading(false)}})()},[]); useEffect(()=>{if(user)loadCash(store)},[store]);
 useEffect(()=>{if(!cash)return;const t=window.setTimeout(()=>{const s=document.querySelector<HTMLSelectElement>('.pdv-context select');if(s){s.value=cash.store;s.dispatchEvent(new Event('change',{bubbles:true}));s.disabled=true}},300);return()=>window.clearTimeout(t)},[cash]);
 async function login(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');setLoading(true);try{const d=await call('login',{identifier,password});setUser(d.user);setPassword('');const c=await call(`cash-session&store=${store}`);setCash(c.cash||null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.')}finally{setLoading(false)}}
 async function recover(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');try{await call('recover-request',{email:identifier});setSuccess('Se o e-mail estiver cadastrado, enviamos as instruções de recuperação.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível solicitar a recuperação.')}}
 async function reset(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');const token=new URLSearchParams(location.search).get('recover')||'';try{await call('recover-reset',{token,password});setSuccess('Senha alterada. Voltando para o login...');setTimeout(()=>{location.href='/pdv'},900)}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar a senha.')}}
 async function openCash(){setError('');setCashLoading(true);try{const d=await call('cash-open',{store,openingAmount:Number(String(opening).replace(',','.'))||0});setCash(d.cash)}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir o caixa.')}finally{setCashLoading(false)}} async function logout(){await call('logout');setUser(null);setCash(null)}
 if(loading)return <><style>{css}</style><main className="pdv-auth-shell"><div className="pdv-auth-card"><div className="pdv-auth-mark">CAPITÃO SUPLEMENTOS</div><p>Preparando o PDV...</p></div></main></>;
 if(!user&&mode==='reset')return <><style>{css}</style><main className="pdv-auth-shell"><form className="pdv-auth-card" onSubmit={reset}><div className="pdv-auth-mark">CAPITÃO SUPLEMENTOS</div><span className="panel-label">RECUPERAÇÃO DE ACESSO</span><h1>Nova senha</h1><p>Crie uma nova senha para seu usuário do PDV.</p>{error&&<div className="pdv-auth-error">⚠️ {error}</div>}{success&&<div className="pdv-auth-success">✓ {success}</div>}<label>Nova senha<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8}/></label><button className="pdv-auth-submit" disabled={password.length<8}>SALVAR NOVA SENHA <ArrowRight size={17}/></button></form></main></>;
 if(!user)return <><style>{css}</style><main className="pdv-auth-shell"><form className="pdv-auth-card" onSubmit={mode==='login'?login:recover}><div className="pdv-auth-mark">CAPITÃO SUPLEMENTOS</div><span className="panel-label">PDV • ACESSO OPERACIONAL</span><h1>{mode==='login'?'Entrar no PDV':'Recuperar senha'}</h1><p>{mode==='login'?'Use seu usuário do PDV. A senha é independente do acesso ao Bling.':'Informe seu e-mail. Se existir um cadastro, enviaremos o link de recuperação.'}</p>{error&&<div className="pdv-auth-error">⚠️ {error}</div>}{success&&<div className="pdv-auth-success">✓ {success}</div>}<label>E-mail ou usuário<input autoFocus value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username"/></label>{mode==='login'&&<label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>}<button className="pdv-auth-submit" disabled={!identifier||(mode==='login'&&!password)}>{mode==='login'?'ENTRAR':'ENVIAR LINK'} <ArrowRight size={17}/></button><button type="button" className="pdv-auth-link" onClick={()=>{setMode(mode==='login'?'recover':'login');setError('');setSuccess('')}}>{mode==='login'?'ESQUECI A SENHA':'VOLTAR PARA LOGIN'}</button><a href="/admin" className="pdv-admin-link">Administração</a></form></main></>;
 if(!cash)return <><style>{css}</style><main className="pdv-auth-shell"><div className="pdv-auth-card pdv-cash-card"><div className="pdv-auth-mark"><Store size={20}/> CAIXA 01</div><span className="panel-label">ABERTURA OPERACIONAL</span><h1>Olá, {user.name.split(' ')[0]}.</h1><p>Antes de iniciar as vendas, abra o caixa da loja.</p><div className="pdv-store-toggle"><button className={store==='camapua'?'active':''} onClick={()=>setStore('camapua')}>CAMAPUÃ</button><button className={store==='newfit'?'active':''} onClick={()=>setStore('newfit')}>NEWFIT</button></div><label>Valor inicial do caixa<input inputMode="decimal" value={opening} onChange={e=>setOpening(e.target.value)} placeholder="R$ 0,00"/></label>{error&&<div className="pdv-auth-error">⚠️ {error}</div>}<button className="pdv-auth-submit" onClick={openCash} disabled={cashLoading}>{cashLoading?'ABRINDO...':'ABRIR CAIXA'} <ArrowRight size={17}/></button><small>Operador: <strong>{user.name}</strong> · Vendedor Bling: <strong>{user.blingSellerName||'não vinculado'}</strong></small><button className="pdv-logout" onClick={logout}><LogOut size={15}/> Sair</button></div></main></>;
 return <><style>{css}</style><Pdv/><button className="pdv-session-chip" onClick={logout}><LockKeyhole size={13}/> {user.name} · {cash.store==='camapua'?'CAMAPUÃ':'NEWFIT'}</button></>;
}
