export const KLAUS_MESSAGES = [
  "Assuma o comando! Seu esforço de hoje constrói o próximo resultado. ⚓ Vamos para a próxima!",
  "Assuma o comando! Seu esforço de hoje constrói o próximo resultado. ⚓ Mantenha o ritmo!",
  "Assuma o comando! Seu esforço de hoje constrói o próximo resultado. ⚓ O próximo resultado começa agora.",
  "Assuma o comando! Seu esforço de hoje constrói o próximo resultado. ⚓ Continue no comando!",
  "Assuma o comando! Seu esforço de hoje constrói o próximo resultado. ⚓ Bora buscar mais!",
  "Capitão está no radar: você manteve a operação em movimento. ⚓ Vamos para a próxima!",
  "Capitão está no radar: você manteve a operação em movimento. ⚓ Mantenha o ritmo!",
  "Capitão está no radar: você manteve a operação em movimento. ⚓ O próximo resultado começa agora.",
  "Capitão está no radar: você manteve a operação em movimento. ⚓ Continue no comando!",
  "Capitão está no radar: você manteve a operação em movimento. ⚓ Bora buscar mais!",
  "Boa atitude. Atendimento firme, foco no cliente e vamos avançar. ⚓ Vamos para a próxima!",
  "Boa atitude. Atendimento firme, foco no cliente e vamos avançar. ⚓ Mantenha o ritmo!",
  "Boa atitude. Atendimento firme, foco no cliente e vamos avançar. ⚓ O próximo resultado começa agora.",
  "Boa atitude. Atendimento firme, foco no cliente e vamos avançar. ⚓ Continue no comando!",
  "Boa atitude. Atendimento firme, foco no cliente e vamos avançar. ⚓ Bora buscar mais!",
  "Resultado começa na abordagem. Continue abrindo oportunidades. ⚓ Vamos para a próxima!",
  "Resultado começa na abordagem. Continue abrindo oportunidades. ⚓ Mantenha o ritmo!",
  "Resultado começa na abordagem. Continue abrindo oportunidades. ⚓ O próximo resultado começa agora.",
  "Resultado começa na abordagem. Continue abrindo oportunidades. ⚓ Continue no comando!",
  "Resultado começa na abordagem. Continue abrindo oportunidades. ⚓ Bora buscar mais!",
  "Você fez sua parte hoje. Amanhã é hora de buscar ainda mais. ⚓ Vamos para a próxima!",
  "Você fez sua parte hoje. Amanhã é hora de buscar ainda mais. ⚓ Mantenha o ritmo!",
  "Você fez sua parte hoje. Amanhã é hora de buscar ainda mais. ⚓ O próximo resultado começa agora.",
  "Você fez sua parte hoje. Amanhã é hora de buscar ainda mais. ⚓ Continue no comando!",
  "Você fez sua parte hoje. Amanhã é hora de buscar ainda mais. ⚓ Bora buscar mais!",
  "Cada venda conta quando o objetivo é crescer com consistência. ⚓ Vamos para a próxima!",
  "Cada venda conta quando o objetivo é crescer com consistência. ⚓ Mantenha o ritmo!",
  "Cada venda conta quando o objetivo é crescer com consistência. ⚓ O próximo resultado começa agora.",
  "Cada venda conta quando o objetivo é crescer com consistência. ⚓ Continue no comando!",
  "Cada venda conta quando o objetivo é crescer com consistência. ⚓ Bora buscar mais!",
  "Excelente trabalho. Agora transforme esse ritmo em padrão. ⚓ Vamos para a próxima!",
  "Excelente trabalho. Agora transforme esse ritmo em padrão. ⚓ Mantenha o ritmo!",
  "Excelente trabalho. Agora transforme esse ritmo em padrão. ⚓ O próximo resultado começa agora.",
  "Excelente trabalho. Agora transforme esse ritmo em padrão. ⚓ Continue no comando!",
  "Excelente trabalho. Agora transforme esse ritmo em padrão. ⚓ Bora buscar mais!",
  "Você está evoluindo. O próximo atendimento pode ser ainda melhor. ⚓ Vamos para a próxima!",
  "Você está evoluindo. O próximo atendimento pode ser ainda melhor. ⚓ Mantenha o ritmo!",
  "Você está evoluindo. O próximo atendimento pode ser ainda melhor. ⚓ O próximo resultado começa agora.",
  "Você está evoluindo. O próximo atendimento pode ser ainda melhor. ⚓ Continue no comando!",
  "Você está evoluindo. O próximo atendimento pode ser ainda melhor. ⚓ Bora buscar mais!",
  "Foco no que você controla: presença, atendimento e atitude. ⚓ Vamos para a próxima!",
  "Foco no que você controla: presença, atendimento e atitude. ⚓ Mantenha o ritmo!",
  "Foco no que você controla: presença, atendimento e atitude. ⚓ O próximo resultado começa agora.",
  "Foco no que você controla: presença, atendimento e atitude. ⚓ Continue no comando!",
  "Foco no que você controla: presença, atendimento e atitude. ⚓ Bora buscar mais!",
  "Uma boa venda é resultado de atenção aos detalhes. ⚓ Vamos para a próxima!",
  "Uma boa venda é resultado de atenção aos detalhes. ⚓ Mantenha o ritmo!",
  "Uma boa venda é resultado de atenção aos detalhes. ⚓ O próximo resultado começa agora.",
  "Uma boa venda é resultado de atenção aos detalhes. ⚓ Continue no comando!",
  "Uma boa venda é resultado de atenção aos detalhes. ⚓ Bora buscar mais!",
  "Você assumiu a frente hoje. Mantenha essa postura amanhã. ⚓ Vamos para a próxima!",
  "Você assumiu a frente hoje. Mantenha essa postura amanhã. ⚓ Mantenha o ritmo!",
  "Você assumiu a frente hoje. Mantenha essa postura amanhã. ⚓ O próximo resultado começa agora.",
  "Você assumiu a frente hoje. Mantenha essa postura amanhã. ⚓ Continue no comando!",
  "Você assumiu a frente hoje. Mantenha essa postura amanhã. ⚓ Bora buscar mais!",
  "Boa operação. Continue ouvindo o cliente e oferecendo a solução certa. ⚓ Vamos para a próxima!",
  "Boa operação. Continue ouvindo o cliente e oferecendo a solução certa. ⚓ Mantenha o ritmo!",
  "Boa operação. Continue ouvindo o cliente e oferecendo a solução certa. ⚓ O próximo resultado começa agora.",
  "Boa operação. Continue ouvindo o cliente e oferecendo a solução certa. ⚓ Continue no comando!",
  "Boa operação. Continue ouvindo o cliente e oferecendo a solução certa. ⚓ Bora buscar mais!",
  "Seu atendimento tem valor. Continue construindo confiança. ⚓ Vamos para a próxima!",
  "Seu atendimento tem valor. Continue construindo confiança. ⚓ Mantenha o ritmo!",
  "Seu atendimento tem valor. Continue construindo confiança. ⚓ O próximo resultado começa agora.",
  "Seu atendimento tem valor. Continue construindo confiança. ⚓ Continue no comando!",
  "Seu atendimento tem valor. Continue construindo confiança. ⚓ Bora buscar mais!",
  "Mais uma etapa vencida. Vamos preparar a próxima conquista. ⚓ Vamos para a próxima!",
  "Mais uma etapa vencida. Vamos preparar a próxima conquista. ⚓ Mantenha o ritmo!",
  "Mais uma etapa vencida. Vamos preparar a próxima conquista. ⚓ O próximo resultado começa agora.",
  "Mais uma etapa vencida. Vamos preparar a próxima conquista. ⚓ Continue no comando!",
  "Mais uma etapa vencida. Vamos preparar a próxima conquista. ⚓ Bora buscar mais!",
  "Quando a oportunidade aparece, atitude faz a diferença. ⚓ Vamos para a próxima!",
  "Quando a oportunidade aparece, atitude faz a diferença. ⚓ Mantenha o ritmo!",
  "Quando a oportunidade aparece, atitude faz a diferença. ⚓ O próximo resultado começa agora.",
  "Quando a oportunidade aparece, atitude faz a diferença. ⚓ Continue no comando!",
  "Quando a oportunidade aparece, atitude faz a diferença. ⚓ Bora buscar mais!",
  "Você mostrou ritmo. Agora vamos buscar consistência. ⚓ Vamos para a próxima!",
  "Você mostrou ritmo. Agora vamos buscar consistência. ⚓ Mantenha o ritmo!",
  "Você mostrou ritmo. Agora vamos buscar consistência. ⚓ O próximo resultado começa agora.",
  "Você mostrou ritmo. Agora vamos buscar consistência. ⚓ Continue no comando!",
  "Você mostrou ritmo. Agora vamos buscar consistência. ⚓ Bora buscar mais!",
  "Bom trabalho. Pequenas melhorias todos os dias geram grandes resultados. ⚓ Vamos para a próxima!",
  "Bom trabalho. Pequenas melhorias todos os dias geram grandes resultados. ⚓ Mantenha o ritmo!",
  "Bom trabalho. Pequenas melhorias todos os dias geram grandes resultados. ⚓ O próximo resultado começa agora.",
  "Bom trabalho. Pequenas melhorias todos os dias geram grandes resultados. ⚓ Continue no comando!",
  "Bom trabalho. Pequenas melhorias todos os dias geram grandes resultados. ⚓ Bora buscar mais!",
  "Capitão confia em quem mantém o foco mesmo nos dias difíceis. ⚓ Vamos para a próxima!",
  "Capitão confia em quem mantém o foco mesmo nos dias difíceis. ⚓ Mantenha o ritmo!",
  "Capitão confia em quem mantém o foco mesmo nos dias difíceis. ⚓ O próximo resultado começa agora.",
  "Capitão confia em quem mantém o foco mesmo nos dias difíceis. ⚓ Continue no comando!",
  "Capitão confia em quem mantém o foco mesmo nos dias difíceis. ⚓ Bora buscar mais!",
  "Você não precisa acertar tudo; precisa continuar evoluindo. ⚓ Vamos para a próxima!",
  "Você não precisa acertar tudo; precisa continuar evoluindo. ⚓ Mantenha o ritmo!",
  "Você não precisa acertar tudo; precisa continuar evoluindo. ⚓ O próximo resultado começa agora.",
  "Você não precisa acertar tudo; precisa continuar evoluindo. ⚓ Continue no comando!",
  "Você não precisa acertar tudo; precisa continuar evoluindo. ⚓ Bora buscar mais!",
  "Fechamos o dia. Guarde o aprendizado e volte mais forte amanhã. ⚓ Vamos para a próxima!",
  "Fechamos o dia. Guarde o aprendizado e volte mais forte amanhã. ⚓ Mantenha o ritmo!",
  "Fechamos o dia. Guarde o aprendizado e volte mais forte amanhã. ⚓ O próximo resultado começa agora.",
  "Fechamos o dia. Guarde o aprendizado e volte mais forte amanhã. ⚓ Continue no comando!",
  "Fechamos o dia. Guarde o aprendizado e volte mais forte amanhã. ⚓ Bora buscar mais!"
];

export const REBECA_MESSAGES = [
  "Muito bem! Seu atendimento de hoje deixou uma marca positiva. ✨ Vamos juntas para o próximo desafio!",
  "Muito bem! Seu atendimento de hoje deixou uma marca positiva. ✨ Continue acreditando!",
  "Muito bem! Seu atendimento de hoje deixou uma marca positiva. ✨ Amanhã tem mais!",
  "Muito bem! Seu atendimento de hoje deixou uma marca positiva. ✨ Seu próximo resultado começa agora.",
  "Muito bem! Seu atendimento de hoje deixou uma marca positiva. ✨ Vamos crescer ainda mais!",
  "Você fez acontecer. Amanhã existe uma nova oportunidade para crescer. ✨ Vamos juntas para o próximo desafio!",
  "Você fez acontecer. Amanhã existe uma nova oportunidade para crescer. ✨ Continue acreditando!",
  "Você fez acontecer. Amanhã existe uma nova oportunidade para crescer. ✨ Amanhã tem mais!",
  "Você fez acontecer. Amanhã existe uma nova oportunidade para crescer. ✨ Seu próximo resultado começa agora.",
  "Você fez acontecer. Amanhã existe uma nova oportunidade para crescer. ✨ Vamos crescer ainda mais!",
  "Atendimento com atenção gera confiança. Continue assim. ✨ Vamos juntas para o próximo desafio!",
  "Atendimento com atenção gera confiança. Continue assim. ✨ Continue acreditando!",
  "Atendimento com atenção gera confiança. Continue assim. ✨ Amanhã tem mais!",
  "Atendimento com atenção gera confiança. Continue assim. ✨ Seu próximo resultado começa agora.",
  "Atendimento com atenção gera confiança. Continue assim. ✨ Vamos crescer ainda mais!",
  "Cada cliente merece presença e cuidado. Você está no caminho certo. ✨ Vamos juntas para o próximo desafio!",
  "Cada cliente merece presença e cuidado. Você está no caminho certo. ✨ Continue acreditando!",
  "Cada cliente merece presença e cuidado. Você está no caminho certo. ✨ Amanhã tem mais!",
  "Cada cliente merece presença e cuidado. Você está no caminho certo. ✨ Seu próximo resultado começa agora.",
  "Cada cliente merece presença e cuidado. Você está no caminho certo. ✨ Vamos crescer ainda mais!",
  "Seu esforço conta. Leve esse aprendizado para o próximo dia. ✨ Vamos juntas para o próximo desafio!",
  "Seu esforço conta. Leve esse aprendizado para o próximo dia. ✨ Continue acreditando!",
  "Seu esforço conta. Leve esse aprendizado para o próximo dia. ✨ Amanhã tem mais!",
  "Seu esforço conta. Leve esse aprendizado para o próximo dia. ✨ Seu próximo resultado começa agora.",
  "Seu esforço conta. Leve esse aprendizado para o próximo dia. ✨ Vamos crescer ainda mais!",
  "Boa jornada! Consistência transforma bons atendimentos em grandes resultados. ✨ Vamos juntas para o próximo desafio!",
  "Boa jornada! Consistência transforma bons atendimentos em grandes resultados. ✨ Continue acreditando!",
  "Boa jornada! Consistência transforma bons atendimentos em grandes resultados. ✨ Amanhã tem mais!",
  "Boa jornada! Consistência transforma bons atendimentos em grandes resultados. ✨ Seu próximo resultado começa agora.",
  "Boa jornada! Consistência transforma bons atendimentos em grandes resultados. ✨ Vamos crescer ainda mais!",
  "Você avançou hoje. Agora vamos construir o próximo passo. ✨ Vamos juntas para o próximo desafio!",
  "Você avançou hoje. Agora vamos construir o próximo passo. ✨ Continue acreditando!",
  "Você avançou hoje. Agora vamos construir o próximo passo. ✨ Amanhã tem mais!",
  "Você avançou hoje. Agora vamos construir o próximo passo. ✨ Seu próximo resultado começa agora.",
  "Você avançou hoje. Agora vamos construir o próximo passo. ✨ Vamos crescer ainda mais!",
  "Excelente! Continue ouvindo, entendendo e oferecendo com confiança. ✨ Vamos juntas para o próximo desafio!",
  "Excelente! Continue ouvindo, entendendo e oferecendo com confiança. ✨ Continue acreditando!",
  "Excelente! Continue ouvindo, entendendo e oferecendo com confiança. ✨ Amanhã tem mais!",
  "Excelente! Continue ouvindo, entendendo e oferecendo com confiança. ✨ Seu próximo resultado começa agora.",
  "Excelente! Continue ouvindo, entendendo e oferecendo com confiança. ✨ Vamos crescer ainda mais!",
  "Um dia de trabalho também é um dia de aprendizado. Guarde o que funcionou. ✨ Vamos juntas para o próximo desafio!",
  "Um dia de trabalho também é um dia de aprendizado. Guarde o que funcionou. ✨ Continue acreditando!",
  "Um dia de trabalho também é um dia de aprendizado. Guarde o que funcionou. ✨ Amanhã tem mais!",
  "Um dia de trabalho também é um dia de aprendizado. Guarde o que funcionou. ✨ Seu próximo resultado começa agora.",
  "Um dia de trabalho também é um dia de aprendizado. Guarde o que funcionou. ✨ Vamos crescer ainda mais!",
  "Você está construindo seu resultado atendimento por atendimento. ✨ Vamos juntas para o próximo desafio!",
  "Você está construindo seu resultado atendimento por atendimento. ✨ Continue acreditando!",
  "Você está construindo seu resultado atendimento por atendimento. ✨ Amanhã tem mais!",
  "Você está construindo seu resultado atendimento por atendimento. ✨ Seu próximo resultado começa agora.",
  "Você está construindo seu resultado atendimento por atendimento. ✨ Vamos crescer ainda mais!",
  "Parabéns pelo empenho. O próximo cliente pode ser uma nova conquista. ✨ Vamos juntas para o próximo desafio!",
  "Parabéns pelo empenho. O próximo cliente pode ser uma nova conquista. ✨ Continue acreditando!",
  "Parabéns pelo empenho. O próximo cliente pode ser uma nova conquista. ✨ Amanhã tem mais!",
  "Parabéns pelo empenho. O próximo cliente pode ser uma nova conquista. ✨ Seu próximo resultado começa agora.",
  "Parabéns pelo empenho. O próximo cliente pode ser uma nova conquista. ✨ Vamos crescer ainda mais!",
  "Seu trabalho faz diferença. Continue acreditando no seu potencial. ✨ Vamos juntas para o próximo desafio!",
  "Seu trabalho faz diferença. Continue acreditando no seu potencial. ✨ Continue acreditando!",
  "Seu trabalho faz diferença. Continue acreditando no seu potencial. ✨ Amanhã tem mais!",
  "Seu trabalho faz diferença. Continue acreditando no seu potencial. ✨ Seu próximo resultado começa agora.",
  "Seu trabalho faz diferença. Continue acreditando no seu potencial. ✨ Vamos crescer ainda mais!",
  "Boa evolução! O segredo é melhorar um pouco a cada dia. ✨ Vamos juntas para o próximo desafio!",
  "Boa evolução! O segredo é melhorar um pouco a cada dia. ✨ Continue acreditando!",
  "Boa evolução! O segredo é melhorar um pouco a cada dia. ✨ Amanhã tem mais!",
  "Boa evolução! O segredo é melhorar um pouco a cada dia. ✨ Seu próximo resultado começa agora.",
  "Boa evolução! O segredo é melhorar um pouco a cada dia. ✨ Vamos crescer ainda mais!",
  "Você esteve presente e fez sua parte. Isso já é uma vitória. ✨ Vamos juntas para o próximo desafio!",
  "Você esteve presente e fez sua parte. Isso já é uma vitória. ✨ Continue acreditando!",
  "Você esteve presente e fez sua parte. Isso já é uma vitória. ✨ Amanhã tem mais!",
  "Você esteve presente e fez sua parte. Isso já é uma vitória. ✨ Seu próximo resultado começa agora.",
  "Você esteve presente e fez sua parte. Isso já é uma vitória. ✨ Vamos crescer ainda mais!",
  "Confiança no atendimento, cuidado com o cliente e foco no resultado. ✨ Vamos juntas para o próximo desafio!",
  "Confiança no atendimento, cuidado com o cliente e foco no resultado. ✨ Continue acreditando!",
  "Confiança no atendimento, cuidado com o cliente e foco no resultado. ✨ Amanhã tem mais!",
  "Confiança no atendimento, cuidado com o cliente e foco no resultado. ✨ Seu próximo resultado começa agora.",
  "Confiança no atendimento, cuidado com o cliente e foco no resultado. ✨ Vamos crescer ainda mais!",
  "Hoje termina; sua próxima oportunidade começa amanhã. ✨ Vamos juntas para o próximo desafio!",
  "Hoje termina; sua próxima oportunidade começa amanhã. ✨ Continue acreditando!",
  "Hoje termina; sua próxima oportunidade começa amanhã. ✨ Amanhã tem mais!",
  "Hoje termina; sua próxima oportunidade começa amanhã. ✨ Seu próximo resultado começa agora.",
  "Hoje termina; sua próxima oportunidade começa amanhã. ✨ Vamos crescer ainda mais!",
  "Você tem capacidade para ir além. Continue praticando e evoluindo. ✨ Vamos juntas para o próximo desafio!",
  "Você tem capacidade para ir além. Continue praticando e evoluindo. ✨ Continue acreditando!",
  "Você tem capacidade para ir além. Continue praticando e evoluindo. ✨ Amanhã tem mais!",
  "Você tem capacidade para ir além. Continue praticando e evoluindo. ✨ Seu próximo resultado começa agora.",
  "Você tem capacidade para ir além. Continue praticando e evoluindo. ✨ Vamos crescer ainda mais!",
  "Ótimo trabalho! Use o resultado de hoje como combustível para amanhã. ✨ Vamos juntas para o próximo desafio!",
  "Ótimo trabalho! Use o resultado de hoje como combustível para amanhã. ✨ Continue acreditando!",
  "Ótimo trabalho! Use o resultado de hoje como combustível para amanhã. ✨ Amanhã tem mais!",
  "Ótimo trabalho! Use o resultado de hoje como combustível para amanhã. ✨ Seu próximo resultado começa agora.",
  "Ótimo trabalho! Use o resultado de hoje como combustível para amanhã. ✨ Vamos crescer ainda mais!",
  "Nem todo dia será igual, mas todo dia pode ensinar alguma coisa. ✨ Vamos juntas para o próximo desafio!",
  "Nem todo dia será igual, mas todo dia pode ensinar alguma coisa. ✨ Continue acreditando!",
  "Nem todo dia será igual, mas todo dia pode ensinar alguma coisa. ✨ Amanhã tem mais!",
  "Nem todo dia será igual, mas todo dia pode ensinar alguma coisa. ✨ Seu próximo resultado começa agora.",
  "Nem todo dia será igual, mas todo dia pode ensinar alguma coisa. ✨ Vamos crescer ainda mais!",
  "Fechamos mais um dia. Respire, recarregue e volte pronta para a próxima missão. ✨ Vamos juntas para o próximo desafio!",
  "Fechamos mais um dia. Respire, recarregue e volte pronta para a próxima missão. ✨ Continue acreditando!",
  "Fechamos mais um dia. Respire, recarregue e volte pronta para a próxima missão. ✨ Amanhã tem mais!",
  "Fechamos mais um dia. Respire, recarregue e volte pronta para a próxima missão. ✨ Seu próximo resultado começa agora.",
  "Fechamos mais um dia. Respire, recarregue e volte pronta para a próxima missão. ✨ Vamos crescer ainda mais!"
];
